<p align="center"> Binu Nair </p>
logo: /assets/img/logo.png
description: 
 <p align="center">
<a href="https://www.linkedin.com/in/binu-nair-756b4275/">LinkedIn</a> |
  <a href="https://github.com/BinuNair357">GitHub</a>
<br>   
  I'm learning Data Science, Machine learning & NLP related problems.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
